### ISSUE TITLE
Get a TypeError when using in DockMonitor

### ISSUE THREAD

**Issue by bobwhitelock** [bvaughn/redux-devtools-filterable-log-monitor#12]
Hi, this looks like a really useful component; I've been wanting something like this for monitoring my store. Unfortunately I can't seem to get it to work within an existing project, after installing and replacing `LogMonitor` with `FilterableLogMonitor` I get the following error: 

`Uncaught TypeError: Monitor.update is not a function(anonymous function) @ createDevTools.js:35`

Here's where I'm creating my store if this helps:

```
import React from 'react';
import { createDevTools } from 'redux-devtools';
import DockMonitor from 'redux-devtools-dock-monitor';
import FilterableLogMonitor from 'redux-devtools-filterable-log-monitor';

export default createDevTools(
  <DockMonitor
    changePositionKey='ctrl-q'
    defaultIsVisible={false}
    defaultPosition="left"
    toggleVisibilityKey='ctrl-h'
    >
    <FilterableLogMonitor />
  </DockMonitor>
);
```

Do you know what I might be missing? Thanks.

**Comment by bvaughn** [comment]
Hey @BobWhitelock. Thank you for saying so. I hope it _is_ useful for you. :)

Hmm. Sounds like the error is happening when [redux-devtools's `createDevTools`](https://github.com/gaearon/redux-devtools/blob/master/src/createDevTools.js#L110) tries to access the `DockMonitor`'s reducer. (In other words it's happening before `FilterableLogMonitor` is even involved.)

`DockMonitor` sets its reducer [here](https://github.com/gaearon/redux-devtools-dock-monitor/blob/master/src/DockMonitor.js#L9) and `FilterableLogMonitor` does the same [here](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/blob/master/src/FilterableLogMonitor.js#L13).

My guess is that you're using an outdated version of `DockMonitor`? I remember it used to set a static `reducer` property before it changed to being `update`. If you look at the original implementation, you can see it [here](https://github.com/gaearon/redux-devtools-dock-monitor/commit/20bb5edbdff2243d5e94bd8af230d35ca5f318e9#diff-e46bd40d37b467ce91b4d53ea3f2b784R8). Try updating that monitor and let me know if that resolves the issue?

**Comment by bobwhitelock** [comment]
That does seem to have been the issue - I was using redux-devtools-dock-monitor `1.0.0-beta-3`, and updating to `1.0.1` fixed this. Thanks for spotting that!

**Comment by bvaughn** [comment]
No problem! Let me know how the filterable log monitor works for you and if you have any suggestions for improvements! :)
