### ISSUE TITLE
TypeError Cannot read property value of nullonActionFilterTextChange 

### ISSUE THREAD

**Issue by kjr247** [bvaughn/redux-devtools-filterable-log-monitor#24]
Hi, this looks like a really useful component; I've been wanting something like this for monitoring my store. Unfortunately I can't seem to get it to work within an existing project, after installing and replacing `LogMonitor`with `FilterableLogMonitor`I get the following error:

Here's where I'm creating my store if this helps:

`Uncaught TypeError: Cannot read property 'value' of nullonActionFilterTextChange @ main.js:1972
complete @ main.js:2160 delayed @ main.js:2170`

```
import React from 'react';
import { createDevTools } from 'redux-devtools';
import DockMonitor from 'redux-devtools-dock-monitor';
import FilterableLogMonitor from 'redux-devtools-filterable-log-monitor';

export default createDevTools(
  <DockMonitor toggleVisibilityKey="ctrl-h" changePositionKey="ctrl-q" defaultIsVisible={false} defaultPosition="left">
    <FilterableLogMonitor/>
  </DockMonitor>
);

```

Do you know what I might be missing? Thanks.

**Comment by bvaughn** [comment]
Here's [the code I'm using](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/blob/master/website/DevTools.js) for [the demo site](https://bvaughn.github.io/redux-devtools-filterable-log-monitor/):

``` js
import React from 'react'
import { createDevTools } from 'redux-devtools'
import DockMonitor from 'redux-devtools-dock-monitor'
import FilterableLogMonitor from 'redux-devtools-filterable-log-monitor'

const DevTools = createDevTools(
  <DockMonitor toggleVisibilityKey='ctrl-h'
               changePositionKey='ctrl-q'
               defaultIsVisible>
    <FilterableLogMonitor/>
  </DockMonitor>
)

export default DevTools
```

Looks like it's basically the exact same code, minus the semis.

I think the error you're referencing must be originating [here](https://github.com/bvaughn/redux-devtools-filterable-log-monitor/blob/47f015be590ed1f65485d552ea1d1e9a4605151c/src/components/ActionFilter.js#L20). I'm not sure why the `event.target` property would be null though. Can you tell me more about the context? Or better yet, point me at a [react.run](http://www.react.run/) example or something?

**Comment by kjr247** [comment]
I'm not very familiar with react.run or how to make one. 
I'll be sure to document everything that I've tried here. So far I've noticed that some of the packages are slightly different versions, but I reluctant to think that is the issue. I ran your project on my machine 

(`npm start`) to prevent any other mistakes and it gets the same error.
 I also tried adding to the demo config 

```
devServer: {
    contentBase: 'build',
    port: 3333
  }
```

and tried running `webpack-dev-server --hot --inline --config webpack.config.demo.js`
which seems to be the biggest difference, and so everything should be pretty dang near the same as what you have deployed on the demo and still no love.

I also tried webpack-dev-server --hot --inline --config webpack.config.dist.js.

**Comment by lparry** [comment]
I'm seeing the same thing :/

**Comment by bvaughn** [comment]
Huh. So you checked out this project, and ran `npm i && npm start` and saw the same error?

**Comment by lparry** [comment]
Nah, I've tried to add it to a project I'm working on this morning, my container is pretty much the same as the one in the docs, getting the same "TypeError Cannot read property value of null" error from the same place.

my container for reference:

``` javascript
import React from "react";
import { createDevTools } from "redux-devtools";
import FilterableLogMonitor from "redux-devtools-filterable-log-monitor";
import DockMonitor from "redux-devtools-dock-monitor";

const ReduxDevTools = createDevTools(
  <DockMonitor toggleVisibilityKey="ctrl-h"
               defaultIsVisible={false}
               changePositionKey="ctrl-q">
    < FilterableLogMonitor />
  </DockMonitor>
);

export default ReduxDevTools;
```

**Comment by bvaughn** [comment]
I see. It's kind of hard for me to diagnose what might be going wrong in a project I'm unfamiliar with.

I just wiped out `node_modules`, re-installed, and ran `npm start` in this project to verify that nothing had been broken by a bad semver update. Things still work in this project.

Afraid I'm going to need more of a reproducible test case from you before I can help further.

**Comment by kjr247** [comment]
I just grabbed the "TodoMVC" demo app from redux or "TodoMVC" from any other redux related project and just added the diff monitor with npm. I tried with several different redux demos... (counter... etc.)

**Comment by kjr247** [comment]
BTW this is pretty great on the demo! I love it!

Shouldn't take more than 2 to 3 minutes to reproduce this depending on your download speeds.
Steps to reproduce:

Just grab the "TodoMVC" demo app from redux-devtools

```
git clone https://github.com/gaearon/redux-devtools.git
cd redux-devtools
npm i
cd examples
cd todomvc
npm i
npm i -d redux-devtools-filterable-log-monitor
npm start
```

Obviously replace the devtools appropriately... 

```
const ReduxDevTools = createDevTools(
  <DockMonitor toggleVisibilityKey="ctrl-h"
               defaultIsVisible={false}
               changePositionKey="ctrl-q">
    < FilterableLogMonitor />
  </DockMonitor>
);
```

from there on out once it runs any inputs to try to filter give that error.

**Comment by bvaughn** [comment]
Thank you :) That's nice to hear.

I am able to reproduce the problem as you describe. Not sure why though. Will look more.

**Comment by bvaughn** [comment]
Hm. Looks like the incoming synthetic event properties are all null

```
onActionFilterTextChange:
SyntheticEvent {
  dispatchConfig: null,
  dispatchMarker: null,
  nativeEvent: null,
  type: null,
  target: null…
}
```

**Comment by bvaughn** [comment]
I wonder if this is because I'm using `lodash.debounce` for the input events

**Comment by bvaughn** [comment]
Some additional testing seems to suggest that _is_ the cause. I wonder why I'm not seeing that same behavior in my projects that use the monitor? hm.

**Comment by bvaughn** [comment]
Version 0.6.1 just released. Should fix the issue you've reported. Thanks for the repro steps!

**Comment by gaearon** [comment]
React recycles event objects. You need to call `e.persist()` if you need that particular event for later use.
Next version of React will warn about this.

**Comment by bvaughn** [comment]
Yup, thanks Dan. I was unaware of that before fixing this issue. For some reason I had not run into it with my own testing or demo project.
