### ISSUE TITLE
Work in conjunction with "standard" redux devtools

### ISSUE THREAD

**Issue by tnrich** [bvaughn/redux-devtools-filterable-log-monitor#25]
Hey there,

Awesome tool!

I'm just wondering if there is a way to use this in conjunction with the "standard" redux devtools. Is that possible, and if so, can you provide an example of how to do it?

Thanks!
Thomas

**Comment by bvaughn** [comment]
Hey @tnrich,

Thank you. :)

I'm a little unsure what you mean. Are you asking if it's possible to use the filterable log monitor along with the vanilla [gaearon/redux-devtools-log-monitor](https://github.com/gaearon/redux-devtools-log-monitor)? The filterable monitor is kind of a superset of functionality so I'm not sure why you'd want to do that. Or are you asking about something else?

**Comment by tnrich** [comment]
Hey @bvaughn , 

Yup that is precisely what I mean. The filterable monitor, unless I'm mistaken, doesn't appear to have the ability to reset, revert, sweep, or commit state. The LogMonitor does provide all of those things. Is there a way to get those pieces of functionality with the filterable monitor you've created?

Thanks again!

**Comment by bvaughn** [comment]
Ah, good point. Unfortunately no. There's no way to use the 2 log monitors together. It's possible that either one could be refactored to decorate the other, but... it would probably have to happen on the non-filtered monitor since the filtered monitor has to inject inputs and also highlight matches.

**Comment by gaearon** [comment]
> There's no way to use the 2 log monitors together.

Technically there is, e.g. see https://github.com/YoruNoHikage/redux-devtools-dispatch/blob/master/src/MultipleMonitors.js. No one just got around to publishing something like this separately and thinking it through :-)

**Comment by bvaughn** [comment]
Haha, fair point @gaearon :) I should have said... "there's no way to compose the 2 monitors"

**Comment by gaearon** [comment]
Why not? MultipleMonitors lets you compose any number of any monitors. It looks like a single monitor itself, so the interface is what createDevTools wants.

**Comment by bvaughn** [comment]
I may be misunderstanding @tnrich's request (so please correct if so) but I imagined he was asking for something more integrated, like this:
![composed-monitors](https://cloud.githubusercontent.com/assets/29597/13028832/400e79b8-d22f-11e5-9f09-061bf821d5c3.png)

The `MultipleMonitors` component just stacks things vertically. I tried it out really quick and giving it both `LongMonitor` and `FilterableLogMonitor` just results in either 1 or the other being visible (whichever is the top z-index). I think that's because both of our monitors expect to fill 100% width/height of their container and the `MultipleMonitors` component isn't wrapping them in separate containers to keep them constrained.

I could submit a PR to `MultipleMonitors` that fixes that (at least a quick local test seems to fix it) but I'm not sure anyone would actually want to stack the monitors like this. Maybe? It looks a little confusing to me :)

![stacked](https://cloud.githubusercontent.com/assets/29597/13028833/46dcd0f0-d22f-11e5-8451-b3b0204c0346.png)

**Comment by bvaughn** [comment]
Maybe creating a separate component that does the Reset, Revert, Sweep, Commit portion would be worth trying?

**Comment by gaearon** [comment]
Stacking wouldn’t be very useful in this case but something like a combobox that lets you choose the current monitor would be IMO. Or you can just add the same buttons to your monitor :-).

cc @YoruNoHikage

**Comment by bvaughn** [comment]
Agreed. Stacking doesn't seem all that hot. I like the idea of a toggle. :)

~~Adding~~ Copying functionality from one monitor to another seems less desirable. I like how most of the monitors around at the moment seem to be pretty focused.

**Comment by YoruNoHikage** [comment]
MultipleMonitors was exclusively made for `redux-devtools-dispatch` at first but when extracting it into a new package, I'd surely make it flexible, tabbing/comboboxing the different devtools could be great.

**Comment by markerikson** [comment]
Okay, two separate thoughts here:
- Does MultipleMonitor support the case of actually trying to put, say, `FirstMonitorType` on the left in one dock, and `SecondMonitorType` on the right in another dock?  Someone was asking about that in Reactiflux the other day, and I couldn't figure out a good way to do it (seemed to be some discussion in the DevTools issues list about it a while back, but nothing concrete).
- I LOVE the filtering ability and the "occurred at" timestamping of the `FilterableLogMonitor`, but the real value of the DevTools comes from being able to time-travel and play with what actions actually occurred.  It doesn't look like the Filterable monitor supports that.

**Comment by bvaughn** [comment]
I'll let YoruNoHikage weigh in on the first question.

> I LOVE the filtering ability and the "occurred at" timestamping of the FilterableLogMonitor, but the real value of the DevTools comes from being able to time-travel and play with what actions actually occurred. It doesn't look like the Filterable monitor supports that.

I suppose `FilterableLogMonitor` could always grow into some of these features. Particularly if you'd be interested in helping. :) Else I can maybe find some time to look into it over the next couple of weeks. I see the value...

**Comment by YoruNoHikage** [comment]
I've succeded displaying two DockMonitors but with their actions being connected, every key you type has effects onto the other DockMonitor, it's not really usable. We could find a way to avoid that maybe.

**Comment by gaearon** [comment]
Note that we support switching multiple monitors inside `DockMonitor` now.

![](https://camo.githubusercontent.com/cc9b9701f3984f3b8cfb6264c214217b0451df09/687474703a2f2f692e696d6775722e636f6d2f51624e7a4e57342e676966)

**Comment by bvaughn** [comment]
Very cool :)

**Comment by bvaughn** [comment]
Doing a little backlog maintenance. The newer [redux-devtools-dock-monitor](https://github.com/gaearon/redux-devtools-dock-monitor) supports multiple monitors as documented [on their README](https://github.com/gaearon/redux-devtools-dock-monitor#multiple-monitors). I just verified that it works well with redux-d:vtools-filterable-log-monitor.

``` js
import React from 'react'
import { createDevTools } from 'redux-devtools'
import DockMonitor from 'redux-devtools-dock-monitor'
import FilterableLogMonitor from 'redux-devtools-filterable-log-monitor'
import LogMonitor from 'redux-devtools-log-monitor'

const DevTools = createDevTools(
  <DockMonitor toggleVisibilityKey='ctrl-h'
               changePositionKey='ctrl-q'
               changeMonitorKey='ctrl-m'
               defaultIsVisible>
    <FilterableLogMonitor/>
    <LogMonitor/>
  </DockMonitor>
)

export default DevTools
```

![untitled screencast 3](https://cloud.githubusercontent.com/assets/29597/14066996/bf2463a6-f40e-11e5-8eb5-ea0c96f5ef00.gif)

So I'm going to close this issue. :)
