### ISSUE TITLE
Automatic scroll

### ISSUE THREAD

**Issue by lauterry** [bvaughn/redux-devtools-filterable-log-monitor#31]
Hello

It would be great to have the monitor automatically scroll to the latest action.

or maybe provide an option to show the latest action on top of the monitor

Best regards

**Comment by bvaughn** [comment]
Hi @lauterry,

That's an interesting suggestion. Would you be interested in contributing? I'd love to review a PR that adds one or the other of the things you mentioned to the monitor. 😄

**Comment by bvaughn** [comment]
Closing due to lack of interest.
