### ISSUE TITLE
Not working if used with other monitors as default view

### ISSUE THREAD

**Issue by mladenp** [bvaughn/redux-devtools-filterable-log-monitor#32]
Small issue, if some other monitor is used (e.g. LogMonitor) as default view and then switch (via changeMonitorKey) to filterable log monitor, its blank, no data is shown.

But it works fine if filterable log monitor is default view.

**Comment by bvaughn** [comment]
Hey @mladenp. If you'd be interested in contributing a fix for this, please do! I'd be happy to review it. :)

**Comment by bvaughn** [comment]
Closing due to lack of interest.
