### ISSUE TITLE
PropTypes and React.createClass deprecation warnings

### ISSUE THREAD

**Issue by mycolaos** [bvaughn/redux-devtools-filterable-log-monitor#34]
**Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.**

**Warning: Highlighter: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.**

Also, found a reference to the same issue here: https://github.com/gaearon/redux-devtools-log-monitor/issues/64

**Comment by bvaughn** [comment]
PRs welcome! 😁

**Comment by bvaughn** [comment]
PropTypes warning resolved via PR #35.

`createClass` warning isn't showing up on the [demo site](https://bvaughn.github.io/redux-devtools-filterable-log-monitor/) so it's already been fixed as far as this project is concerned. 😄
