### ISSUE TITLE
Show/Hide by cookie

### ISSUE THREAD

**Issue by edtoken** [bvaughn/redux-devtools-filterable-log-monitor#37]
Hello! In our project we added one convenient feature.
Auto show/hide after page refresh by cookie value `DevTools:defaultShow`

And, developers can enable/disable panel from cookie.
Now, we moved it value to localstorage.

What do you think about this?
Maybe, it's feature for redux-devtools and read value from it?

**Comment by bvaughn** [comment]
Did you mean to file this as an issue on [gaearon/redux-devtools](https://github.com/gaearon/redux-devtools)? Doens't seem like it's specific to this project (redux-devtools-filterable-log-monitor).

**Comment by bvaughn** [comment]
Closing for now because I assume you meant to file against the main redux-devtools project. 😄

**Comment by edtoken** [comment]
Sorry, thanks))))
