### ISSUE TITLE
Update dependencies (React 15)

### ISSUE THREAD

**Issue by edtoken** [bvaughn/redux-devtools-filterable-log-monitor#38]
Hello.
I would like to update the dependencies and make small fixes with this (so far this update is only for React 15)
In the next few days I will make a pool request (everything is ready, it is necessary to check)
Thanks!

![2017-12-13 19 21 38](https://user-images.githubusercontent.com/4567083/33949560-ff8280c6-e03a-11e7-8e2a-2c28e1dc124c.png)
![2017-12-13 19 21 51](https://user-images.githubusercontent.com/4567083/33949566-02af7e2a-e03b-11e7-8970-96c1c7be97e2.png)

**Comment by bvaughn** [comment]
I believe the only thing _required_ is to update the `peerDependencies` block to also support React 16, no? This project doesn't _actually_ install React for you. It defers that to your project.

**Comment by bvaughn** [comment]
Not sure I understand the motivation behind this. Could you explain?

For example, your screenshot shows updating `prop-types` from `^15.5.0` to `^15.6.0`, but this isn't actually necessary. If you install this project now, NPM will pull in the latest 15.x release (which would be `15.6.0`). No update necessary to install that newer version. However, if you raise the minimum version from `^15.5.0` to `^15.6.0` then anyone who might happen to have 15.5 installed _would_ get an incompatible warning.

As I mentioned on the other issue (#39), I think that all that's required here is to update the `peerDependencies` block to also support React 16, eg: `"react": "^0.14.0 || ^15.0.0 || ^16.0.0"`.

**Comment by bvaughn** [comment]
I don't think there's anything to do here. Please correct me if I'm wrong, but for now I'm going to close this issue.
