### ISSUE TITLE
Demo breaks when "Update State" button is pressed

### ISSUE THREAD

**Issue by ghost** [bvaughn/redux-devtools-filterable-log-monitor#9]
![bug](https://cloud.githubusercontent.com/assets/1812608/11939100/82ccf1a6-a7d4-11e5-8297-76ef2e5d050e.gif)

**Comment by ghost** [comment]
The issue was seen on Chromium. Works fine in Chrome and Firefox.

**Comment by bvaughn** [comment]
Chromium user! I award you... the stick of shame

<img src='http://static.comicvine.com/uploads/scale_super/4/40928/2475283-shame_stick.jpg'/>
